package.json, src/vesper-metadata.json
This PR adds the vLINK pool to the list of Vesper pools.
=> vLINK pool

src/vesper-metadata.json
To have more and better information about the pools and its life-cycles.
=> Add which pools superseded the retired ones

package.json, src/vesper-metadata.json
Update valid vUSDC migration paths.
=> Update migration paths

package-lock.json, package.json, src/vesper-metadata.json
This PR adds the new aggressive vDAI pool to the `alpha` (internal development/testing) stage.
=> Aggressive vDAI pool

package-lock.json, package.json, src/vesper-metadata.json
This PR adds a new vDAI pool to the list of Ethereum pools.
=> Add a new vDAI pool

.github/CODEOWNERS
=> Set code owners

package-lock.json, package.json, src/vesper-metadata.json
Update the stage of vaETH and prepare the release of a new version of the package.
=> Graduate vaETH to beta

package-lock.json, package.json, src/vesper-metadata.json
Add VSP token Polygon contract data.
=> Add Polygon VSP token

.github/pull_request_template.md, package-lock.json, package.json, src/vesper-metadata.json
vMATIC was tested and is ready for the beta stage. This PR updates that.
=> Graduate vMATIC to beta

package-lock.json, package.json, src/vesper-metadata.json
=> Graduate vaDPI to prod

.github/CODEOWNERS
Add Martin as code owner so he is able to merge commits and publish new versions if/when needed.
=> Add Martin as code owner

package-lock.json, package.json, src/vesper-metadata.json
This PR updates the MiniArmyKnife to its new address in [0x583e4938f95e75906b1b69514c9bf7ebc648201a](https://etherscan.io/address/0x583e4938f95e75906b1b69514c9bf7ebc648201a)
=> Update MiniArmyKnife address

scripts/add-pool.js
This PR updates add-pool script in order to support Avalanche pools.
=> Update add-pool script to support Avalanche pools

package-lock.json, package.json, src/vesper-metadata.json, test/vesper-metadata.spec.js
This PR adds the new AVAX vaDAI pool and upgrades Polygon vaDAI pool to version 4.
=> Add AVAX vaDAI 

package-lock.json, package.json, src/vesper-metadata.json
This PR removes veDAI-PUNK pool
=> Remove vedaipunk

package-lock.json, package.json, src/vesper-metadata.json
This PR updates MiniArmyKnife address
=> Update mak address

package.json, src/vesper-metadata.json
This PR updates veETH-DAI to version 4
=> Upgrade veETH-DAI to v4

package-lock.json, package.json, src/vesper-metadata.json
This PR upgrades veWBTC-DAI pool to v4
=> Upgrade veWBTC-DAI to v4

package-lock.json, package.json, src/vesper-metadata.json
This PR adds synth controller for Avalanche
=> Add synth controller

package-lock.json, package.json, src/vesper-metadata.json
=> Vaape orbit

package-lock.json, package.json, src/vesper-metadata.json
This PR replaces Avalanche vaAVAX pool.
=> Update avalanche vaavax

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates Avalanche vaAVAX to beta
=> Graduate vaavax

package-lock.json, package.json, src/vesper-metadata.json
This PR adds VSP on Avalanche network
=> Add VSP token on Avalanche

package-lock.json, package.json, scripts/add-pool.js, src/vesper-metadata.json, test/vesper-metadata.spec.js
This PR adds Avalanche vaUSDC.n pool on beta.
=> Add avalanche vausdc n

package-lock.json, package.json, src/vesper-metadata.json, test/vesper-metadata.spec.js
This PR updates Avalanche pool names and symbols and graduates Ava vaUSDC and vaQI to prod
=> Graduate ava vausdc

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates vaFRAX to prod
=> Graduate vafrax

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates veDAI-VSP to beta
=> Graduate dai-vsp

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates veUSDC-LMR pool to prod
=> Graduate veusdc lmr

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates vaSTETH to prod
=> Graduate vaSTETH

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates veFRAX-FRAXBP to prod
=> Graduate veFRAX-FRAXBP

package-lock.json, package.json, src/logos/vareth.svg, src/vesper-metadata.json
This PR adds vaRETH pool on beta. Also adds vaRETH logo.
Actual effort: 2h
=> Add vareth

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates vaRETH pool to prod.
=> Graduate vareth

package-lock.json, package.json, scripts/add-pool.js, src/vesper-metadata.json
This PR updates vesper-metadata and new pool script in order to add more information about the pool collateral. This updates doesn't affect retro-compatibility but in the future we may want to remove pool.asset property, that can be replaced with collateral.symbol
Actual effort: 3h
=> More collateral data

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates vaCBETH pool to beta.
=> Graduate va cbeth beta

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates vaCBETH pool to prod
=> Graduate vacbeth

.github/workflows/test.yml, package-lock.json, package.json, scripts/add-pool.js, src/vesper-metadata.json, test/vesper-metadata.spec.js
This PR adds Optimism chain support and Optimism vaETH pool on alpha.
Actual effort: 2h
=> Add optimism vaeth

package-lock.json, package.json, src/vesper-metadata.json
This PR adds Optimism vaUSDC pool on alpha
=> Add op vausdc

package-lock.json, package.json, src/vesper-metadata.json
=> Retire vaBUSD

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates vaOP Optimism pool to beta.
=> Graduate vaop beta

package-lock.json, package.json, src/vesper-metadata.json
This PR graduates vaWSTETH Optimism pool to prod.
=> Graduate va wsteth

package-lock.json, package.json, src/vesper-metadata.json
This PR retires the vVSP pool.
=> Retire vVSP

.github/workflows/test.yml, package-lock.json, package.json, scripts/add-pool.js, src/vesper-metadata.json, test/vesper-metadata.spec.js
=> Add BASE support

package-lock.json, package.json, src/vesper-metadata.json
This PR adds base compounding tokens details
=> Base compounding tokens
